name: tranquil
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.1.0
  animated_splash_screen: ^1.3.0
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rxdart: ^0.27.5

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf  
